spring:
  mustache:
    expose-session-attributes: true
    suffix: .html
  datasource: 
    url: jdbc:h2:~/boot_blog
    driver-class-name: org.h2.Driver
    username: sa
    password:  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
